export type Company = {
  id: string;
  name: string;
  logo: string;
  isOk: boolean;
  city?: string;
  state?: string;
  country?: string;
  description?: string;
  replacements?: Company[];
};

export const companies: Company[] = [
  {
    name: "Kentucky Fried Chicken",
    id: "1",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Kfc_logo.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_11",
        isOk: true,
        name: "Al-Baik",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Al-Baik-logo.png",
      },
    ],
    city: "لويفيل",
    state: "كنتاكي",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم الوجبات السريعة العالمية المعروفة بدجاجها المقلي",
  },
  {
    name: "McDonald's",
    id: "2",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/McDonalds-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_21",
        isOk: true,
        name: "Kudu",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Kudu-Logo.png",
      },
    ],
    city: "سان برناردينو",
    state: "كاليفورنيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم الوجبات السريعة العالمية المتخصصة بالهامبرجر",
  },
  {
    name: "Pepsi",
    id: "3",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Pepsi-logo.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_31",
        isOk: true,
        name: "Panda",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Panda-logo.png",
      },
    ],
    city: "نيو بيرن",
    state: "كارولاينا الشمالية",
    country: "الولايات المتحدة الأمريكية",
    description: "شركة المشروبات الغازية العالمية المعروفة بمشروب بيبسي الغازي",
  },
  {
    name: "Coca-Cola",
    id: "4",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Coca-Cola-Logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_41",
        isOk: true,
        name: "Qawha",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Qawha-logo.png",
      },
    ],
    city: "أتلانتا",
    state: "جورجيا",
    country: "الولايات المتحدة الأمريكية",
    description: "شركة المشروبات الغازية العالمية المعروفة بمشروب كوكاكولا",
  },
  {
    name: "Lay's",
    id: "5",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Lays-logo.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_51",
        isOk: true,
        name: "Chipsico",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Chipsico-logo.png",
      },
    ],
    city: "بلانو",
    state: "تكساس",
    country: "الولايات المتحدة الأمريكية",
    description: "علامة تجارية عالمية للوجبات الخفيفة معروفة برقائق البطاطس",
  },
  {
    name: "Burger King",
    id: "6",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Burger-King-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_61",
        isOk: true,
        name: "Mr. Burger",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Mr.-Burger-logo.png",
      },
    ],
    city: "ميامي",
    state: "فلوريدا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم الوجبات السريعة العالمية المتخصصة بالبرجر",
  },
  {
    name: "Starbucks",
    id: "7",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Starbucks-Logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_71",
        isOk: true,
        name: "Coffee Republic",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Coffee-Republic-logo.png",
      },
    ],
    city: "سياتل",
    state: "واشنطن",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مقاهي عالمية متخصصة بالقهوة",
  },
  {
    name: "Subway",
    id: "8",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Subway-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_81",
        isOk: true,
        name: "Super Sandwich",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Super-Sandwich-logo.png",
      },
    ],
    city: "ميلفورد",
    state: "كونيتيكت",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية متخصصة بالساندويتشات",
  },
  {
    name: "Pizza Hut",
    id: "9",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Pizza-Hut-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_91",
        isOk: true,
        name: "Pizza Planet",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Pizza-Planet-logo.png",
      },
    ],
    city: "ويتشيتا",
    state: "كانساس",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم عالمية متخصصة بالبيتزا",
  },
  {
    name: "KFC",
    id: "10",
    logo: "https://1000logos.net/wp-content/uploads/2017/05/KFC-Logo.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_101",
        isOk: true,
        name: "Al Baik",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Al-Baik-logo.png",
      },
    ],
    city: "لويفيل",
    state: "كنتاكي",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم الوجبات السريعة العالمية المعروفة بدجاجها المقلي",
  },
  {
    name: "Taco Bell",
    id: "11",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Taco-Bell-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_111",
        isOk: true,
        name: "Taco Halal",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Taco-Halal-logo.png",
      },
    ],
    city: "إيرفاين",
    state: "كاليفورنيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم عالمية متخصصة بالتاكو المكسيكية ",
  },
  {
    name: "Krispy Kreme",
    id: "12",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Krispy-Kreme-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_121",
        isOk: true,
        name: "Krispy Karak",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Krispy-Karak-logo.png",
      },
    ],
    city: "وينستون-سالم",
    state: "كارولاينا الشمالية",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مخابز عالمية متخصصة بالدونات",
  },
  {
    name: "Dunkin' Donuts",
    id: "13",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Dunkin-Donuts-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_131",
        isOk: true,
        name: "Donuts Galore",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Donuts-Galore-logo.png",
      },
    ],
    city: "كانتون",
    state: "أوهايو",
    country: "الولايات المتحدة الأمريكية",
    description: " سلسلة مخابز عالمية متخصصة بالدونات",
  },
  {
    name: "Domino's Pizza",
    id: "14",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Dominos-pizza-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_141",
        isOk: true,
        name: "Pizza Point",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Pizza-Point-logo.png",
      },
    ],
    city: "آن أربور",
    state: "ميشيغان",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة توصيل بيتزا عالمية",
  },
  {
    name: "Papa John's",
    id: "15",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Papa-Johns-Pizza-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_151",
        isOk: true,
        name: "Pizza Palace",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Pizza-Palace-logo.png",
      },
    ],
    city: "جيفرسونفيل",
    state: "تينيسي",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم بيتزا عالمية",
  },
  {
    name: "Wendy's",
    id: "16",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Wendys-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_161",
        isOk: true,
        name: "Wendy's Arabian Grill",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Wendys-Arabian-Grill-logo.png",
      },
    ],
    city: "كولومبس",
    state: "جورجيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية",
  },
  {
    name: "Chick-fil-A",
    id: "17",
    logo: "https://1000logos.net/wp-content/uploads/2017/05/Chick-fil-A-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_171",
        isOk: true,
        name: "ChickenCo",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/ChickenCo-logo.png",
      },
    ],
    city: "أتلانتا",
    state: "جورجيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم دجاج ووجبات سريعة عالمية",
  },
  {
    name: "Dairy Queen",
    id: "18",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Dairy-Queen-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_181",
        isOk: true,
        name: "Ice Cream Land",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Ice-Cream-Land-logo.png",
      },
    ],
    city: "إدجرتون",
    state: "ويسكونسن",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم آيس كريم عالمية",
  },
  {
    name: "Baskin Robbins",
    id: "19",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Baskin-Robbins-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_191",
        isOk: true,
        name: "Frosty Treats",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Frosty-Treats-logo.png",
      },
    ],
    city: "برلينغتون",
    state: "فيرمونت",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة متاجر آيس كريم عالمية",
  },
  {
    name: "Arby's",
    id: "20",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Arbys-logo.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_201",
        isOk: true,
        name: "Shawarma House",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Shawarma-House-logo.png",
      },
    ],
    city: "سان دييغو",
    state: "كاليفورنيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية",
  },
  {
    name: "Popeyes",
    id: "21",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Popeyes-Louisiana-Kitchen-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_211",
        isOk: true,
        name: "Chicking",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Chicking-logo.png",
      },
    ],
    city: "لينكولن",
    state: "نبراسكا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم دجاج ووجبات سريعة عالمية",
  },
  {
    name: "Chipotle",
    id: "22",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Chipotle-Mexican-Grill-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_221",
        isOk: true,
        name: "Wrap It Up",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Wrap-It-Up-logo.png",
      },
    ],
    city: "سان دييغو",
    state: "كاليفورنيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم مكسيكية عالمية",
  },
  {
    name: "Sonic",
    id: "23",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Sonic-Drive-In-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_231",
        isOk: true,
        name: "Super Sonic",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Super-Sonic-logo.png",
      },
    ],
    city: "غلينديل",
    state: "كاليفورنيا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية",
  },
  {
    name: "Little Caesars",
    id: "24",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Little-Caesars-Pizza-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_241",
        isOk: true,
        name: "Pizza Prince",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Pizza-Prince-logo.png",
      },
    ],
    city: "سانت لويس",
    state: "ميزوري",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم بيتزا عالمية",
  },
  {
    name: "Jack in the Box",
    id: "25",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Jack-In-The-Box-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_251",
        isOk: true,
        name: "Jacks Burgers",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Jacks-Burgers-logo.png",
      },
    ],
    city: "نيو هوب",
    state: "مينيسوتا",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية",
  },
  {
    name: "Carl's Jr.",
    id: "26",
    logo: "https://1000logos.net/wp-content/uploads/2017/03/Carls-Jr-logo-500x313.png",
    isOk: false,
    replacements: [
      {
        id: "isOK_261",
        isOk: true,
        name: "Carl's Arabic Grill",
        logo: "https://1000logos.net/wp-content/uploads/2020/04/Carls-Arabic-Grill-logo.png",
      },
    ],
    city: "سكوكي",
    state: "إلينوي",
    country: "الولايات المتحدة الأمريكية",
    description: "سلسلة مطاعم وجبات سريعة عالمية",
  },
];
